spring:
  application:
    name: profileMnt
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    # TODO : allowPublicKeyRetrieval=true
    url: jdbc:mysql://mysqlDB:3306/demo_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: itsmart
    password: itsmart1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:static/, file:/opt/profileMnt/uploads/images/ # 정적 리소스 경로설정
mybatis:
  mapper-locations: classpath:sqlMapper/*.xml
  type-aliases-package: kr.co.itsmart.profileMnt.vo
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

debug: false
management.endpoints.web.exposure.exclude: "*"

logging:
  level:
    kr.co.itsmart.profileMnt: debug
    org.springframework.web.servlet: debug

user:
  default-password: itsmart1!

file:
  upload-dir: /opt/profileMnt/uploads/images