spring:
  application:
    name: profileMnt
  devtools:
    restart:
      enabled: false
  security:
    jwt:
      secret-key: 7JWI64WV7ZWY7IS47JqU7J206rKD7J2A7Iuc7YGs66a/7YKk7JiI7Jes7JWE7J207Yuw7Iqk66eI7Yq4
      expiration: 300000 # 5 min
      refresh-token:
        expiration: 86400000 # 1 day

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://mysqlDB:3306/demo_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: itsmart
    password: itsmart1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      encoding: utf-8
  web:
    resources:
      static-locations: classpath:static/, file:/opt/profileMnt/uploads/images/, file:/opt/profileMnt/uploads/excel/ # 정적 리소스 경로설정
mybatis:
  mapper-locations: classpath:sqlMapper/*.xml
  type-aliases-package: kr.co.itsmart.profileMnt.vo
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

debug: false
management.endpoints.web.exposure.exclude: "*"

logging:
  level:
    kr.co.itsmart.profileMnt: debug
    org.springframework.web.servlet: debug

user:
  default-password: itsmart1!

file:
  upload-photo-dir: /opt/profileMnt/uploads/images
  upload-excel-dir: /opt/profileMnt/uploads/excel
